In [342]:
# Data Preproccessing
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import numpy as np # linear algebra



In [343]:
df = pd.read_csv('Mobile_Dataset.csv')

In [344]:
df

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [345]:
dataset = df.values

In [346]:
dataset

array([[8.420e+02, 0.000e+00, 2.200e+00, ..., 0.000e+00, 1.000e+00,
        1.000e+00],
       [1.021e+03, 1.000e+00, 5.000e-01, ..., 1.000e+00, 0.000e+00,
        2.000e+00],
       [5.630e+02, 1.000e+00, 5.000e-01, ..., 1.000e+00, 0.000e+00,
        2.000e+00],
       ...,
       [1.911e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 0.000e+00,
        3.000e+00],
       [1.512e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [5.100e+02, 1.000e+00, 2.000e+00, ..., 1.000e+00, 1.000e+00,
        3.000e+00]])

In [347]:
X = dataset[:,0:20]

In [348]:
Y = dataset[:,20]

In [349]:
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)

In [350]:
X_scale

array([[0.22778891, 0.        , 0.68      , ..., 0.        , 0.        ,
        1.        ],
       [0.34736139, 1.        , 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.04141617, 1.        , 0.        , ..., 1.        , 1.        ,
        0.        ],
       ...,
       [0.94188377, 0.        , 0.16      , ..., 1.        , 1.        ,
        0.        ],
       [0.6753507 , 0.        , 0.16      , ..., 1.        , 1.        ,
        1.        ],
       [0.00601202, 1.        , 0.6       , ..., 1.        , 1.        ,
        1.        ]])

In [351]:
Y = df['price_range']

In [352]:
X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X_scale, Y, test_size=0.3 , random_state=42)

In [353]:
X_val_and_test

array([[0.76486306, 0.        , 0.8       , ..., 1.        , 1.        ,
        0.        ],
       [0.45490982, 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.98263193, 0.        , 0.96      , ..., 1.        , 1.        ,
        0.        ],
       ...,
       [0.03607214, 1.        , 0.        , ..., 0.        , 1.        ,
        1.        ],
       [0.36539746, 1.        , 0.4       , ..., 1.        , 0.        ,
        0.        ],
       [0.3740815 , 1.        , 0.64      , ..., 1.        , 1.        ,
        0.        ]])

In [354]:
X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.5)

In [355]:
print(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)

(1400, 20) (300, 20) (300, 20) (1400,) (300,) (300,)


In [391]:
from keras.models import Sequential
from keras.layers import Dense
from keras.losses import SparseCategoricalCrossentropy
from keras.optimizers import Adam

model = Sequential([
 Dense(32, activation="relu", input_shape=(20,)),
 Dense(32,activation='relu'),
 Dense(4,activation='softmax')
])
model.compile(
   loss = SparseCategoricalCrossentropy(),
   optimizer = Adam(),
   metrics="accuracy")

In [392]:
model.fit(X_train,Y_train,epochs=100)

Epoch 1/100
44/44 [==============================] - 0s 2ms/step - loss: 1.3570 - accuracy: 0.3057
Epoch 2/100
44/44 [==============================] - 0s 2ms/step - loss: 1.2872 - accuracy: 0.4086
Epoch 3/100
44/44 [==============================] - 0s 2ms/step - loss: 1.1554 - accuracy: 0.5286
Epoch 4/100
44/44 [==============================] - 0s 2ms/step - loss: 0.9723 - accuracy: 0.6257
Epoch 5/100
44/44 [==============================] - 0s 2ms/step - loss: 0.8224 - accuracy: 0.6971
Epoch 6/100
44/44 [==============================] - 0s 2ms/step - loss: 0.7196 - accuracy: 0.7579
Epoch 7/100
44/44 [==============================] - 0s 2ms/step - loss: 0.6393 - accuracy: 0.7800
Epoch 8/100
44/44 [==============================] - 0s 2ms/step - loss: 0.5809 - accuracy: 0.8007
Epoch 9/100
44/44 [==============================] - 0s 2ms/step - loss: 0.5237 - accuracy: 0.8286
Epoch 10/100
44/44 [==============================] - 0s 2ms/step - loss: 0.4845 - accuracy: 0.8379
Epoch 11/

In [390]:
model.evaluate(X_test, Y_test)[1]

10/10 [==============================] - 0s 2ms/step - loss: 0.1440 - accuracy: 0.9367


0.9366666674613953

In [374]:
# creates an array of predictions from a matrix of percentages of classifications
def predictionrelease(preds):
    arr=[]
    for i in range(0,len(preds)):
        ans=np.argmax(preds[i])
        arr.append(ans)
    len(arr)
    return arr

In [378]:
 #testing our cross val sets
preds_test = model.predict(X_test)      
test_preds = predictionrelease(preds_test)

10/10 [==============================] - 0s 1ms/step


In [377]:
from sklearn.metrics import classification_report,confusion_matrix
#cross validation
print(classification_report(Y_test,test_preds)) 


              precision    recall  f1-score   support

           0       0.99      0.95      0.97        74
           1       0.90      0.94      0.92        66
           2       0.92      0.89      0.91        75
           3       0.94      0.96      0.95        85

    accuracy                           0.94       300
   macro avg       0.94      0.94      0.94       300
weighted avg       0.94      0.94      0.94       300

